version: '3.7'

services:
  app:
    container_name: animage_server
    build: .
    volumes:
      - .:/animage_server
      - node_modules:/animage_server/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:deltaforce@db:5432/animage-db
    command: >
      sh -c "echo 'Running migrations...' &&
             npx sequelize-cli db:migrate &&
             echo 'Running seeders...' &&
             npx sequelize-cli db:seed:all &&
             echo 'Starting app...' &&
             npm run dev"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    container_name: animage_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deltaforce
      POSTGRES_DB: animage-db
    ports:
      - 5432:5432
  
volumes:
  node_modules:
  db: